---
- name: Deploy docker-compose service
  become: true
  ansible.builtin.template:
    src: docker-compose@.service.j2
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
- name: Download and install docker-compose
  become: true
  ansible.builtin.get_url:
    url: '{{ docker_compose_url }}'
    dest: /usr/local/bin/docker-compose
    mode: '0755'
