---
galaxy_info:
  author: Yannick Sebastia
  description: Configurer selinux on host
  license: GPL-3.0-only
  min_ansible_version: '2.1'
  namespace: ysebastia
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
dependencies:
  - role: ysebastia.base.selinux
    when:
      - docker_seboolean | length > 0
