---
- name: Ensure Docker is installed
  become: true
  ansible.builtin.apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - python3
      - python3-pip
    update_cache: true
