---
- name: Ensure Docker is installed
  become: true
  ansible.builtin.dnf:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - python3
      - python3-pip
      - python3-pip-wheel
